# Site
title: "Cozinha Nômade"

# URL
url: ''
baseurl: ''
permalink: :title/
include: ['_pages']
collections:
  potes:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown
port: 6543
future: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "potes"
    values:
      layout: "page"

# Data
social:
  facebook: ""
  instagram: "https://www.instagram.com/acozinhanomade"
  github: ""
  twitter: ""
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:acozinhanomade@gmail.com"
twitter_user: "SiloLatitude"
