# Site
title: "a COZINHA NÔMADE"

# URL
url: 'http://acozinhanomade.ml'
baseurl: ''
permalink: :title/
include: ['_pages']
collections:
  potes:
    output: false
  receitas:
    output: true
    permalink: /:collection/:name/

# Build settings
markdown: kramdown
port: 6543
future: false

# Defaults
defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_receitas"
      type: "receitas"
    values:
      layout: "page"

# Data
social:
  facebook: ""
  instagram: "https://www.instagram.com/acozinhanomade"
  github: ""
  twitter: ""
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:acozinhanomade@gmail.com"
twitter_user: "SiloLatitude"
